### ISSUE TITLE
Use with MPU9255

### ISSUE THREAD

**Issue by korbinianbauer** [hideakitai/MPU9250#12]
In case anyone wants to use this great lib with the MPU9255:

In MPU9250.h just change the line

`const uint8_t MPU9250_WHOAMI_DEFAULT_VALUE {0x71}; // 0x68????`

to

`const uint8_t MPU9250_WHOAMI_DEFAULT_VALUE {0x73}; // 0x68????`

**Comment by hideakitai** [comment]
@korbinianbauer Thanks! I've supported MPU9255.
