### ISSUE TITLE
How to get compass heading

### ISSUE THREAD

**Issue by CTSchorsch** [hideakitai/MPU9250#13]
Hi,
i want to use this library for a compass application. can you tell me how to get the heading with the quaternion filter function ? 
Thans
Georg

**Comment by korbinianbauer** [comment]
Heading == yaw.

`mpu.getYaw()`

**Comment by CTSchorsch** [comment]
Thx!
Is it tilt compensated?

Georg

**Comment by korbinianbauer** [comment]
As far as I can tell, yes.

**Comment by CTSchorsch** [comment]
Thx a lot !
