### ISSUE TITLE
No function to change the sampling rate  

### ISSUE THREAD

**Issue by tanmay-1srivastava** [hideakitai/MPU9250#19]
Can anyone please help me write a function to set the ODR of the accelerometer and gyroscope? Thank you in advance #

**Comment by hideakitai** [comment]
Maybe I can but please send me PR if you can.  I think it's better to add setting struct for advanced  setting, so I'll do that if I have time.

**Comment by hideakitai** [comment]
@tanmay-1srivastava I've added some extension to customize MPU9250 settings. Please try it.
