### ISSUE TITLE
Code for Determining Heading

### ISSUE THREAD

**Issue by AndrewNoviello** [hideakitai/MPU9250#29]
Hi,
I was wondering if you would be able to provide some sample code for calculating heading from magnetometer values in your library. I am a little confused as to how to do this myself- thanks so much!

**Comment by hideakitai** [comment]
Hi, roll, pitch and yaw are automatically calculated. Just use `getYaw()` to get heading (heading is same as yaw).

**Comment by hideakitai** [comment]
Maybe using `getYaw()` solves your problem. I'm going to close this issue, but if you have any problem, please reopen it.
