### ISSUE TITLE
Could you share your eeprom library?

### ISSUE THREAD

**Issue by enginergun** [hideakitai/MPU9250#4]
Firstly thanks for your excellent mpu9250 library. It is very usefull. I want to write sensor's offsets to eeprom but your calibration_eeprom sketch is giving library error, i found a library (https://github.com/thijse/Arduino-EEPROMEx) but it also giving error. " class EEPROMClassEx has no member named 'commit' and has no member named 'begin'. " How can i solve this problem? 

Thank you.

**Comment by hideakitai** [comment]
I'm sorry for late reply.
What platform do you use? Some platform may not be able to compile `calibration_eeprom.ino`.

**Comment by enginergun** [comment]
Thanks for reply it's not late for me :) I'm using arduino mega 2560

**Comment by hideakitai** [comment]
I have added an example for Uno/Mega board. Though I haven't check if it works, please check it out!
