### ISSUE TITLE
Need help to implement mpu9250 code in a project

### ISSUE THREAD

**Issue by Tonymazzz** [hideakitai/MPU9250#40]
Hello guys!

Can you help me to implement your code into this project please??

https://github.com/n1rml/esp32_airmouse/issues/1

Im losted... Thank you in advance!! 🙌🙌🙌

**Comment by hideakitai** [comment]
Sorry, I don't have time to write the code for that project. If you want me to write the code instead of you, let me know from email as a job.

Please let me know if you have the problem about MPU9250 library.

**Comment by Tonymazzz** [comment]
I will send you an email! Thanks your really sir.
