### ISSUE TITLE
磁気センサのデータ取得

### ISSUE THREAD

**Issue by nopnop2002** [hideakitai/MPU9250#5]
こんにちは

M5Stackを入手しましたので、内蔵されているMPU9250を利用するために、
こちらのライブラリを試してみました。
examples\simpleを実行したところ、roll,pitch,yahはそれらしく変化しますが、
テーブルの上に置いて水平方向に回転させても、mx,my,mzの値が変化しません。

MPU9250を使って自分が置かれている東西南北の向きを知ることはできないのでしょうか？？

**Comment by hideakitai** [comment]
@nopnop2002 こんにちは、ご報告ありがとうございます。ご連絡遅くなりまして恐縮です。手元のM5Stack Coreでsimple.inoを書き込んでみましたが、mx my mz も取れているようです。環境は、macOS 10.14.4, Arduino 1.89, esp32 1.02 (from Board Manager), Board = ESP32 Dev Module といった感じです。もう一度お試しいただけますか？

**Comment by nopnop2002** [comment]
こんばんは。
ご連絡ありがとうございます。
もう一度試してみます。

**Comment by hideakitai** [comment]
@nopnop2002 こちら大丈夫でしたかね。一旦クローズします！
