### ISSUE TITLE
Cant compile for CubeCell

### ISSUE THREAD

**Issue by ShreddinPB** [hideakitai/MPU9250#59]
Hello, this seems to be a conflict with some of the CubeCell built in libraries. There is a file in the CubeCell libraries that match the name of one in this library, MPU9250.h. I remove the file from the CubeCell directory and I still cant compile the examples from this library. I have to remove the whole CubeCell directory and thus remove support for the board itself to get the examples from this library to compile. 
I know this isnt a "issue" with your library, just a conflict, but I didnt know where else to try to solve this ;)
The error I get is:
"Using library MPU9250 at version 0.4.6 in folder: C:\Users\jrigg\Documents\Arduino\libraries\MPU9250 
exit status 1
'MPU9250' does not name a type
"
Thank you!

**Comment by hideakitai** [comment]
@ShreddinPB Hi, thank you for reporting. I've also tried to compile it with the CubeCell board example. But at first, it seems that the compiler does not support C++11. If you really want to use my MPU9250 in your project with the CubeCell, please contact the maintainer of CubeCell https://github.com/HelTecAutomation/CubeCell-Arduino
