### ISSUE TITLE
I2C Error Code : 2 while being detected as an MPU6500 in connection_check

### ISSUE THREAD

**Issue by filipppp** [hideakitai/MPU9250#60]
I'm pretty sure I'm doing something wrong here, but I cant connect my MPU9250 i ordered from Ali with this library. 

I get an I2C Error Code : 2 

I used the connection_check for checking the connection and I'm getting this.

```
Searching for i2c devices...
Found 1 I2C devices
I2C addresses are: 0x68 
I2C address 0x68 is MPU6500 and ready to use

```

I set the AD0 Pin to LOW and the SCL/SDA pins accordingly (and the 5V and GND pins accordingly) so no more pins only these 5 pins are connected. 

I know that the MPU9250 is a combination of an MPU6500 and an Magnetometer, but somehow I think it cant seem to find the latter one.

**Comment by hideakitai** [comment]
Yes, maybe there is no AK8963. You may be able to use this library with additional AK8963 module.

**Comment by filipppp** [comment]
@hideakitai I seem to have the same issue as here in #52 , but sadly don't know how to fix it
