### ISSUE TITLE
Yaw Values

### ISSUE THREAD

**Issue by beratgnr** [hideakitai/MPU9250#62]
Yaw values does not match with compass. Also when I rotate the sensor 90 degree , Yaw value changes 40-50 degree. I can not fix that , I am using simple with callibration code. How can I fix that.

**Comment by hideakitai** [comment]
Hi, there seems to be a problem with the calibration. Can you try again?

**Comment by beratgnr** [comment]
Hi, thank you for answering. Do I need calibrate the magnetometer in flat plane or 3D calibration with rotating every angle?

**Comment by hideakitai** [comment]
First, please stay still on the flat plane until the accel/gyro calibration finishes. After that, rotate the device around.

**Comment by beratgnr** [comment]
Thank you

30 Eyl 2021 Per 14:19 tarihinde Hideaki Tai ***@***.***> şunu
yazdı:

**Comment by MotoMotoRo** [comment]
Hello !
how can I change the magnetometer scale  to 0 >> 360 ...?
Thank you in advance.

**Comment by beratgnr** [comment]
> Hello ! how can I change the magnetometer scale to 0 >> 360 ...? Thank you in advance.
Maybe belove algorithm can work. 

![IMG_20220531_141414](https://user-images.githubusercontent.com/91346044/171160985-d4337504-354a-4f56-b980-9955f6858cd1.jpg)

**Comment by MotoMotoRo** [comment]
Thanks for the help.
