### ISSUE TITLE
Help with a modified version of this lib (yaw axis issue)

### ISSUE THREAD

**Issue by paulosincos** [hideakitai/MPU9250#66]
Hi,

First of all, thanks @hideakitai for your great work on this library.

I submitted a issue a week ago and you help me to discover I have only an MPU6500 instead of a traditional mpu9250 (here #65 and here #52)

After some a little code review, lots os google searchs, looking for alternative libraries, I managed to change your library to work with only mpu6500.

In fact, I don't changed the code, I only completly removed the magnetometer code, then I revised the register map with the documentation of manufacturer of 6500 and when finishing, I added a new quarternion filter of Madwick that don't need magnetometer to calculate (https://www.enib.fr/~kerhoas/RESEAU_CAPTEURS_/code.txt/MadgwickAHRS.cpp, looks similar to yours).

All worked fine... except for the yaw axis:

![image](https://user-images.githubusercontent.com/4800671/136278928-caebda20-4c9e-45b5-a36d-4bd3ac6f57a2.png)

Even after calibrating, and I tryied lots of calibrations, my Yaw always keeps "moving", like the sensor is slowing rotating.

I have no ideia if it is as know issue, that I can resolve with some parameter, or if it is a issue with my hardware.

Roll and pitch works correctly.

If anyone has any tip for me, I'll extremelly grateful

Thanks

(sorry my potato english)

**Comment by hideakitai** [comment]
@paulosincos Hi, It is a known and common problem. To solve it, we put in a geomagnetic sensor and make it 9DOF. For example, please refer 
https://community.nxp.com/t5/Sensors/6DOF-GY-KALMAN-Yaw-drift/m-p/457552

**Comment by paulosincos** [comment]
> @paulosincos Hi, It is a known and common problem. To solve it, we put in a geomagnetic sensor and make it 9DOF. For example, please refer https://community.nxp.com/t5/Sensors/6DOF-GY-KALMAN-Yaw-drift/m-p/457552

Thank you very much!
