### ISSUE TITLE
Opposite direction orientation

### ISSUE THREAD

**Issue by roboticsai** [hideakitai/MPU9250#67]
When i run the code provided in the README and test it, the orientation is comming opposite i.e i rotate the imu 90 degree clockwise the z axis rotation data is comming just opposite.

**Comment by hideakitai** [comment]
@roboticsai Hi, which coordinate do you use? Please let me know detailed information. README saids,

> The coordinate of quaternion and roll/pitch/yaw angles are basedd on airplane coordinate (Right-Handed, X-forward, Z-down). On the other hand, the coordinate of euler angle is based on the axes of acceleration and gyro sensors (Right-Handed, X-forward, Z-up).Please use getEulerX/Y/Z() for euler angles and getRoll/Pitch/Yaw() for airplane coordinate angles.

**Comment by hideakitai** [comment]
@roboticsai I think it's a problem about coordinate/placement as mentioned above. I'm closing this issue, but please feel free to reopen it if you still have a problem.
