### ISSUE TITLE
Pitch & Roll are affecting Yaw values 

### ISSUE THREAD

**Issue by EngAhmed53** [hideakitai/MPU9250#68]
This is not an issue but a question, I'm trying the Simple with Calibration sketch, I noticed that when I pitch or roll, the yaw values are affected, is this an expected behaviour?
I think that yaw should not affect this much while pitching or rolling.
I have attached a screenshot.
[Screenshot from serial ploter](https://drive.google.com/file/d/17VXbEaiAH6GU_PN5P1qFbeCaq3rVieLG/view?usp=sharing)

**Comment by hideakitai** [comment]
Hi @EngAhmed53  , there seems to be a general problem with the calibration. Please also refer #62 . If you still have the problem, please feel free to reopen this issue.
