### ISSUE TITLE
Unable to get consistent euler angles

### ISSUE THREAD

**Issue by prabodhprakash** [hideakitai/MPU9250#69]
Hardware:
MPU9250:
https://www.xcluma.com/mpu-9250-gy-9250-mpu9250-nine-axis-sensor-module-i2c-spi-communication?search=9250

ESP8266MOD:
https://handsontec.com/index.php/product/esp8266-remote-serial-wifi-module/

Connection:
```
ESP8266MOD         MPU9250
5V------------------VCC
GND-----------------GND
D2------------------SDA
D1------------------SCL
```
To setup biases: I calibrated my sensor 5 times using `calibration.ino` and averaged out the values. 

Code:

```
#include "MPU9250.h"

MPU9250 mpu;

void setup() {
    Serial.begin(115200);
    Wire.begin();
    delay(2000);

    if (!mpu.setup(0x68)) {  // change to your own address
        while (1) {
            Serial.println("MPU connection failed. Please check your connection with `connection_check` example.");
            delay(5000);
        }
    }

    mpu.setAccBias(66.23, 16.95, -240.16);
    mpu.setGyroBias(5.08, 6.27, -10.43);
    mpu.setMagBias(290.34, 147.44, -441.84);
    mpu.setMagScale(0.90, 1.16, 0.97);
    mpu.setMagneticDeclination(-1.14);
    mpu.setFilterIterations(10);
}

void loop() {
    if (mpu.update()) {
        static uint32_t prev_ms = millis();
        if (millis() > prev_ms + 250) {
            print_roll_pitch_yaw();
            prev_ms = millis();
        }
    }
}

void print_roll_pitch_yaw() {
    Serial.print("Euler X, Y, Z: ");
    Serial.print(mpu.getEulerX(), 2);
    Serial.print(", ");
    Serial.print(mpu.getEulerY(), 2);
    Serial.print(", ");
    Serial.println(mpu.getEulerZ(), 2);
}
```

Problem:
Unable to get consistent euler angles in any direction.

If I rotate the sensor perpendicular - the expectation is that one of the (x, y, z) should change by 90 - however, on some axis it changes by 180 and on other axis it changes less than 90.

Kindly help

**Comment by hideakitai** [comment]
@prabodhprakash Hi, thank you for reporting.  Please

- check if the device is the real MPU-9250 (see #52 )
- try `simple_with_calibration` example first 
- check if the averaged offsets/bias units are correct (calibration values shown in a console in examples are not the same as the value that should be set)

**Comment by prabodhprakash** [comment]
The sensor has this written:

9250/9255/6500/6555 and if you open this link:
https://www.xcluma.com/mpu-9250-gy-9250-mpu9250-nine-axis-sensor-module-i2c-spi-communication?search=9250
- it has something 92.65 written on one side (can you please check)

Prabodh Prakash

**Comment by prabodhprakash** [comment]
I tried other libraries as well - but couldn't get it work :-(

**Comment by hideakitai** [comment]
I'm sorry to hear that... I don't think it's a problem with this library, so I'm closing this issue. But I wish you good luck with your project! You can fuse raw sensor values manually with an external library like this : [MadgwickAHRS](https://github.com/arduino-libraries/MadgwickAHRS)
