### ISSUE TITLE
Questions regarding the Accelerometer and restoring calibration data

### ISSUE THREAD

**Issue by ben-mkiv** [hideakitai/MPU9250#73]
Hi,

i have some problems getting stable results for linear acceleration from an MPU9250, there's always some drift when not moving (xyz -0.03 / 0.7 / 0.2)

also i wonder if the bias spectrum after calibration is normal (sensor not moving and laying on a table)
```
calibration results for gyro bias x/y/z:
-191.37 / -196.88 / -115.29
-198.98 / -192.62 / -120.78
-199.63 / -199.31 / -120.95
-207.12 / -197.96 / -111.72
-198.98 / -194.12 / -114.87
-197.97 / -188.78 / -124.05

calibration results for accelerometer bias x/y/z:
-114.54 / 1097.17 / -257.56
 -97.46 / 1124.93 / -297.34
-109.60 / 1117.49 / -293.11
-109.14 / 1124.04 / -295.03
-105.88 / 1131.42 / -299.98
 -97.45 / 1111.29 / -318.20
```

code used to read the values
```c
mpu.calibrateAccelGyro();

Serial.println("calibration results for gyro bias x/y/z:");
Serial.print(mpu.getGyroBiasX());
Serial.print(" / ");
Serial.print(mpu.getGyroBiasY());
Serial.print(" / ");
Serial.print(mpu.getGyroBiasZ());
Serial.println("");
       
Serial.println("calibration results for accelerometer bias x/y/z:");
Serial.print(mpu.getAccBiasX());
Serial.print(" / ");
Serial.print(mpu.getAccBiasY());
Serial.print(" / ");
Serial.print(mpu.getAccBiasZ());
Serial.println("");
```

second, i can't figure out how to restore the bias values, i save them by storing the result of the functions used in the code above (data is written and read correct from the eeprom), however they have no effect after setting them with the corresponding methods
`mpu.setAccBias();` and `mpu.setGyroBias();`

some more debug information of the startup process
```
MPU9250 WHO AM I = 71
AK8963 WHO AM I = 48
Mag Factory Calibration Values: 
X-Axis sensitivity offset value 1.19
Y-Axis sensitivity offset value 1.19
Z-Axis sensitivity offset value 1.15
x-axis self test: acceleration trim within : 0.6% of factory value
y-axis self test: acceleration trim within : -0.2% of factory value
z-axis self test: acceleration trim within : 6.4% of factory value
x-axis self test: gyration trim within : -2.4% of factory value
y-axis self test: gyration trim within : 0.5% of factory value
z-axis self test: gyration trim within : 0.5% of factory value
```

**Comment by hideakitai** [comment]
@ben-mkiv Sorry for the late reply.

Drifts are mainly caused by poor calibration. Please retry to calibrate it.

[calibrate_eeprom](https://github.com/hideakitai/MPU9250/blob/master/examples/calibration_eeprom/calibration_eeprom.ino) example shows how to save/load calibrated results. Please try it.

Please feel free to reopen this issue if you still have the problem.
