### ISSUE TITLE
How to use FIFO functionality

### ISSUE THREAD

**Issue by JRoseCPMax** [hideakitai/MPU9250#74]
Hey, just saw there is the possibility to set the FIFO Samplerate. Is there also the possibility to access the builtin FIFO Buffer? Id like to get Accel readings at very high sample rates without having to poll the sensor nonstop. 
Or is it already using the buffer and .update() or .available() will return true as long as there is a value in the buffer?

**Comment by hideakitai** [comment]
@JRoseCPMax Hi, sorry for the late reply. There is no way to use FIFO with this library. Also, I don't plan to support FIFO with this library. But you can use it directly with I2C. Please refer to the datasheet for details.
