### ISSUE TITLE
Understanding acc and gyro calibration

### ISSUE THREAD

**Issue by pezosanta** [hideakitai/MPU9250#79]
Hi @hideakitai !

I would like to understand how acc and gyro calibration works. 

Below is the orientation of the accelerometer axes according to the MPU9250 [documentation](https://www.hestore.hu/prod_getfile.php?id=9347).
![image](https://user-images.githubusercontent.com/30471303/153857119-c79ee2bb-114f-4644-9992-28d51468d58b.png)

**CASE I**
Placing the imu plane on the table (just like in the illustration below) and calibrate it in that position.
![normal_z](https://user-images.githubusercontent.com/30471303/153858070-269479d8-9388-45a9-8078-4e67b740ef4d.png)
The measured values seems correct:
```
Acc_x: 0.00048828125
Acc_y: 0.00146484375
Acc_z: 1.00146484375
```
![image](https://user-images.githubusercontent.com/30471303/153864486-a278eb50-016a-4c16-a3e4-45df35a2f5bd.png)

**CASE II/a**
Placing the imu differently, with the y axes pointing down (see the illustration below) and calibrate it in that position.
![rotated_y](https://user-images.githubusercontent.com/30471303/153862348-2fd0ca6b-4ee0-47d1-9429-d9c561b178dc.png)
After calibration, I get odd measurements values (imu is still in the same position as it was during the calibration).
```
Acc_x: -0.013671875
Acc_y: -0.4892578125
Acc_z: -1.08642578125
```
![image](https://user-images.githubusercontent.com/30471303/153862876-e54916eb-b54f-4700-9395-71eea70d6d22.png)

**CASE II/b**
After calibrating the imu in **CASE II/a** position, during measurements, move the imu into **CASE I** position (so z axes points upwards).
**Now it seems like the y axes and the z axes are virtually mixed up.**  Is this behaviour intentional? That would mean that the imu can only be used (with calibration) correctly if it placed like in **CASE I**.
![image](https://user-images.githubusercontent.com/30471303/153862071-7dba7694-a53b-47e5-8a12-4b528387e689.png)

Am I doing something wrong? Or the imu can really be calibrated correctly only in horizontal (CASE I) position?

**Comment by hideakitai** [comment]
Sorry for the late reply. Please calibrate with the horizontal (CASE I) position.
