### ISSUE TITLE
5 different MPU9250 and not a single one 100% working (broken axis)

### ISSUE THREAD

**Issue by simkard69** [hideakitai/MPU9250#81]
Hello everyone,

I'm tryting to get this lib working, and I think it does pretty well except the fact that when I'm trying to read from each sensor I have (4x GY-91 and 1x GY-9250), not a single one seems to give 3 working axis for Accel and/or Gyro.
The 3 magnetometer axis are systematically ok (maybe much more resistant than the ones from accel/gyro).

I always get 1 axis or 2 not working per sensor on accel and/or gyro ... very frustrating.

Can someone help me out with those ? maybe it's just a calibration problem ... or maybe these sensors are just 5h177y ones systematically ?

Thanks

**Comment by hideakitai** [comment]
Sorry, I can support only MPU-9250.
