### ISSUE TITLE
Heading compass

### ISSUE THREAD

**Issue by TobiIchiro1** [hideakitai/MPU9250#84]
What getMag() do i use to meake a heading compass? please help me

**Comment by yarikpetrenko** [comment]
Hello. To get heading you use this function - mpu.getYaw(). You can upload simple sketch https://github.com/hideakitai/MPU9250#usage where it's print heading, pitch and roll

**Comment by pieteroskam** [comment]
Yes, simply use getYaw... 
Otherwise you could use the line below
`float(atan2(mpu.getMagY(), mpu.getMagX())) * RAD_TO_DEG`
