### ISSUE TITLE
How to get yaw rate of change based on Gyro and Quaternions.

### ISSUE THREAD

**Issue by pieteroskam** [hideakitai/MPU9250#85]
I'm making this auto pilot for my boat. I got your library to work on my ESP32 with a sort of stable yaw. (took good calibration, noise free environment).

Now for my autopilot I need the rate of change of the yaw. I'm running my Control loop at 10HZ but the readings of yaw between loops can be 0.2 degree's thus 2 deg/s. I could also use the GyroZ to get the yaw rate of change. If the boat is horizontal, this would workin deg/s. Now a sailboat rolls and pitches continuous with waves. That GyroZ won't be correct to get the yaw-rate-of-change. 

Now I tried to understand Quaternions and rotating them but after 2 days I have given up. So my question is how do I get the Gyro values of the horizontal plane (earths plane). Ideally I also want to gave gyro for Pitch and Heel for future functions.

UPDATE. Solved it using math's i did understand.  Code below will show the Rotation speed perpendicular to the earths plane

`
float pitch = mpu.getPitch()*deg2rad;

  float heel = mpu.getRoll()*deg2rad;

  float Z = 0;

  Z = mpu.getGyroZ() * cos(pitch) * cos(heel);

  Z += mpu.getGyroY() * sin(heel);

  Z += mpu.getGyroX() * sin(pitch);

`

![Screenshot 2022-06-17 224617](https://user-images.githubusercontent.com/4243523/174398956-d3d5816c-41ce-4fb9-a4a0-865f445e040f.png)

**Comment by hideakitai** [comment]
Thanks for your excellent knowledge!
