### ISSUE TITLE
I don't know which pins should be connected to esp32 to use this library

### ISSUE THREAD

**Issue by bbhxwl** [hideakitai/MPU9250#86]
mpu.setup(0x68)

I don't know which pins should be connected to esp32 to use this library

Does the above code need to be modified? I don't understand. What is the address?

**Comment by pieteroskam** [comment]
I run the library on a esp32, no changes needed. address is 0x68

Run the connection check example and you get more info where it fails.

**Comment by Tanmax-Payne** [comment]
The Pins on my DoIt DevKit V1 are as follows - 
SDA - 21
SCL - 22
