### ISSUE TITLE
get Acc data

### ISSUE THREAD

**Issue by mjoksiglandi** [hideakitai/MPU9250#9]
hi, 
i need use Acc data for decremental speed, how i get the data, y use mpu.getAcc() but dont work, help me please

**Comment by korbinianbauer** [comment]
Use `mpu.getAcc(0)` to get the acceleration in the x-axis. 
Use `mpu.getAcc(1)` to get the acceleration in the y-axis. 
Use `mpu.getAcc(2)` to get the acceleration in the z-axis. 

The unit used here is g, so an output of 1.0 means ~9.81m/s²

**Comment by hideakitai** [comment]
Sorry for late reply, I've added some easy to use getter. Thanks!
