### ISSUE TITLE
The linear acceleration values for the x- and y-axes are strange.

### ISSUE THREAD

**Issue by go-kyoul** [hideakitai/MPU9250#90]
## Environment

IDE (Arduino IDE, PlatformIO, etc.) :  Arduino IDE
Board/MCU (Arduino Uno, ESP32, etc.): ESP32
Board Firmware Version (see board manager): 2.0.6
MPU-9250 Library Version: latest

## Problem Summary
The linear acceleration values for the x- and y-axes are strange.

## Problem Details
When the sensor is not moving, if the sensor is tilted, mpu.getLinearAccX() and mpu.The getLinearAccY() value is not zero. its values are such as (1.0,-1.0) or (-1.0, 1.0), (1.0, 1.0), (-1.0, -1.0), when it on vertical angle. depending on the angle, two values are change, but it is not zero although the sensor is not moving.

**Comment by hideakitai** [comment]
Please calibrate your chip correctly and try again
